import { ContentModule } from './content/content.module';
import { AppRoutingModule } from './app-routing.module';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { NavbarComponent } from './navbar/navbar.component';
import { FooterComponent } from './footer/footer.component';
import { SideNavComponent } from './side-nav/side-nav.component';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { Store } from './store';
import { MenuService } from './content/services/menu/menu.service';

import { environment } from 'environments/environment';
import { AngularFireModule } from '@angular/fire';
import { AngularFirestoreModule } from '@angular/fire/firestore';




@NgModule({
  declarations: [
    AppComponent,
    NavbarComponent,
    FooterComponent,
    SideNavComponent,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    ContentModule,
    BrowserAnimationsModule,
    AngularFireModule.initializeApp(environment.firebase),
    // AngularFireDatabaseModule, imports firebase/database, only needed for database features
    // AngularFireAuthModule, imports firebase/auth, only needed for auth features
    AngularFirestoreModule,
],
  providers: [ Store, MenuService],
  bootstrap: [AppComponent]
})
export class AppModule {}
